### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ravil99** [zuhairabbas14/Decorators-in-Action#1]
You made a good looking code, but I have some points to mention and questions to ask:
1) It's quite funny, but we use the same quadratic_equation solver, because it's the first link in Google, leading to StackOverFlow solution. That's funny!
2) As I understood, you use only class decorator from task_3 in your main file. So I can't evaluate the correctness of your other 3 tasl.
3) In task3 you open "output.txt" in "w" mode and use this file for all 4 functions. So you rewrite the output of all functions, except for the last one. I think you can fix it, assigning different names to files.
4) Your README could be bigger

**Comment by zuhairabbas14** [comment]
Thanks for the review!

1. Yes, it's taken from Geeks4geeks for testing purposes. It's funny that most of us used it.
2. Yes, I used task 3 for the demonstration to keep main.py simple, but we can test all the other tasks by simply assigning different decorators to the testing functions. Also, one of the reasons to choose task 3 is that it covers almost all the other aspects except exception handling.
3. Good point, I will update that.
4. I Agree, just keeping it simple.
